# Generated by Django 5.0.3 on 2024-06-11 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])])),
            ],
        ),
    ]
