# Generated by Django 5.0.3 on 2024-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfiles',
            name='fileRead',
            field=models.BooleanField(default=False),
        ),
    ]
