# Generated by Django 5.0.3 on 2024-06-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='emissionDate',
            field=models.DateField(),
        ),
    ]
